import 'user_data.dart';

/// Target environment for the verification API
enum ApprovalEnvironment { development, production }

/// Verification modules supported by CreditChek Approval
enum ApprovalModule { identity, liveliness, income, recova, credit }

class ApprovalConfig {
  /// Your CreditChek public API key
  final String publicKey;

  /// Environment mode (defaults to [ApprovalEnvironment.development])
  final ApprovalEnvironment environment;

  /// List of verification modules (defaults to `[ApprovalModule.identity]`)
  final List<ApprovalModule> modules;

  /// Optional pre-fill data for the user
  final AUserData? userData;

  /// Unique session UUID generated by your backend via /v1/auth/widget-session/create
  final String sessionId;

  const ApprovalConfig({
    required this.publicKey,
    required this.sessionId,
    this.environment = ApprovalEnvironment.development,
    this.modules = const [ApprovalModule.identity],
    this.userData,
  });

  Map<String, dynamic> toMap() {
    return {
      'publicKey': publicKey,
      'environment': environment == ApprovalEnvironment.production
          ? 'PRODUCTION'
          : 'DEVELOPMENT',
      'modules': modules.map((m) => m.name.toUpperCase()).toList(),
      'userData': userData?.toMap(),
      'sessionId': sessionId,
    };
  }
}
